### ISSUE TITLE
Problem importing library

### ISSUE THREAD

**Issue by iainfreestone** [deQuota/chartist-to-image#1]
Hi, I came across your library from one of the issues on Chartist regarding creating an image from the SVG chart but when I add import chartist2image from 'chartist-to-image'; to my application I get the following. 

```
./node_modules/chartist-to-image/chartist-to-image.js

Module not found: Can't resolve 'dom-to-image' in 'D:\xxxxxxxxxx\report\html-docx-js\html-docx\node_modules\chartist-to-image'
```

I can see the file named dom-to-image.js in the node_modules/chartist-to-image.

I am trying to run this within a basic [create react app](https://github.com/facebook/create-react-app)

Any idea why this might be?

Many thanks

**Comment by deQuota** [comment]
Hi @iainfreestone ,
I looked into this matter.
I have built this npm module for Angular 2,4,5 however I managed to get this working on react :) 

The following code (App.js) renders an image of HTML div 'root', you can change it to ChartistChart's div id. Also pass the Chartist instance to toJepg() function.

` import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import chartist2image from 'chartist-to-image';

class App extends Component {


    async genImage() {
        let base64;
        let options = {
            outputImage: {
                quality: 1.00,
                bgcolor: '#000000',
                name: 'my-chartist-charts'
            },
            format: 'jpeg',
            download: true,
            log: true,

        };
        await chartist2image.toJpeg('root',options).then(
            (res) => {
                base64 = res;
                console.log('Logged >>>>>>>>', base64);
            }
        );
    }

    render() {
        return (
            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo"/>
                    <h1 className="App-title">Welcome to React</h1>
                </header>
                <p className="App-intro">
                    To get started, edit <code>src/App.js</code> and save to reload.
                </p>
                <button onClick={this.genImage()}>GenImage</button>
            </div>
        );
    }
}

export default App; `

Hope this helps :)

**Comment by iainfreestone** [comment]
Excellent. That works as expected many thanks.

**Comment by deQuota** [comment]
welcome @iainfreestone  :) 
Since the problem has been solved, I'm closing this issue.

**Comment by deQuota** [comment]
welcome @iainfreestone  :)
Since the problem has been solved, I'm closing this issue.
