### ISSUE TITLE
I Installed the package but cannot be imported 

### ISSUE THREAD

**Issue by m7ammad7assan** [deQuota/chartist-to-image#3]
I installed it using NPM in nagular 7 but import statements not working !!

**Comment by deQuota** [comment]
Can I know what option you have used while importing from following two?

import chartist2image from 'chartist-to-image';
or
import * as chartist2image from 'chartist-to-image';

It's better to use second option,

**Comment by deQuota** [comment]
@m7ammad7assan  I have added the additional dependency library, try npm install again.
If not working yet, please do `npm install dom-to-image --save`

**Comment by deQuota** [comment]
Since in version 1.2.1 package dom-to-image has been added as a dependency, I'm closing this issue.
